content:
  - name: services
    label: Services
    type: file
    path: data/services/services.json
    format: json
    list: true

    fields:
      - name: title
        label: Service Name
        type: string

      - name: description
        label: Description
        type: text

      - name: price
        label: Price
        type: string

      - name: link
        label: Link
        type: string

      - name: image
        label: Image
        type: string

      - name: video
        label: Video
        type: string
